export const SET_UP_FIREBASE = "SET_UP_FIREBASE";

export const SIGN_IN_USER = 'SIGN_IN_USER'; // used in redux-saga
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';

export const SIGN_OUT_USER = 'SIGN_OUT_USER'; // used in redux-saga
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_ERROR = 'SIGN_OUT_USER_ERROR';

export const SET_UP_USER = 'SET_UP_USER'; // used in redux-saga
export const SET_UP_USER_SUCCESS = 'SET_UP_USER_SUCCESS';
export const SET_UP_USER_ERROR = 'SET_UP_USER_ERROR';

export const LOAD_OFFICE_USERS = 'LOAD_OFFICE_USER';
export const LOAD_OFFICE_USERS_SUCCESS = 'LOAD_OFFICE_USER_SUCCESS';
export const LOAD_OFFICE_USERS_ERROR = 'LOAD_OFFICE_USER_ERROR';

export const LOAD_CONFERENCE_ROOMS = 'LOAD_CONFERENCE_ROOM';
export const LOAD_CONFERENCE_ROOMS_SUCCESS = 'LOAD_CONFERENCE_ROOM_SUCCESS';
export const LOAD_CONFERENCE_ROOMS_ERROR = 'LOAD_CONFERENCE_ROOM_ERROR';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_ERROR = 'LOAD_NOTIFICATIONS_ERROR';

export const CREATE_USER_FOR_OFFICEADMIN = 'CREATE_USER_FOR_OFFICEADMIN';
export const CREATE_USER_FOR_OFFICEADMIN_FINISHED = 'CREATE_USER_FOR_OFFICEADMIN_FINISHED';

export const REMOVE_OFFICE_USER = 'REMOVE_OFFICE_USER';
export const REMOVE_OFFICE_USER_FINISHED = 'REMOVE_OFFICE_USER_FINISHED';

export const EDIT_OFFICE_USER = 'EDIT_OFFICE_USER';
export const EDIT_OFFICE_USER_FINISHED = 'EDIT_OFFICE_USER_FINISHED';
