export const SET_UP_FIREBASE = "SET_UP_FIREBASE";

export const SIGN_IN_USER = 'SIGN_IN_USER'; // used in redux-saga
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';

export const SIGN_OUT_USER = 'SIGN_OUT_USER'; // used in redux-saga
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_ERROR = 'SIGN_OUT_USER_ERROR';

export const SET_UP_USER = 'SET_UP_USER'; // used in redux-saga
export const SET_UP_USER_SUCCESS = 'SET_UP_USER_SUCCESS';
export const SET_UP_USER_ERROR = 'SET_UP_USER_ERROR';

export const LOAD_OFFICE_USERS = 'LOAD_OFFICE_USER';
export const LOAD_OFFICE_USERS_SUCCESS = 'LOAD_OFFICE_USER_SUCCESS';
export const LOAD_OFFICE_USERS_ERROR = 'LOAD_OFFICE_USER_ERROR';

export const LOAD_CONFERENCE_ROOMS = 'LOAD_CONFERENCE_ROOM';
export const LOAD_CONFERENCE_ROOMS_SUCCESS = 'LOAD_CONFERENCE_ROOM_SUCCESS';
export const LOAD_CONFERENCE_ROOMS_ERROR = 'LOAD_CONFERENCE_ROOM_ERROR';

export const LOAD_HOT_DESKS = 'LOAD_HOT_DESKS';
export const LOAD_HOT_DESKS_SUCCESS = 'LOAD_HOT_DESKS_SUCCESS';
export const LOAD_HOT_DESKS_ERROR = 'LOAD_HOT_DESKS_ERROR';

export const LOAD_REGISTERED_GUESTS = 'LOAD_REGISTERED_GUESTS';
export const LOAD_REGISTERED_GUESTS_SUCCESS = 'LOAD_REGISTERED_GUESTS_SUCCESS';
export const LOAD_REGISTERED_GUESTS_ERROR = 'LOAD_REGISTERED_GUESTS_ERROR';

export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_ERROR = 'LOAD_EVENTS_ERROR';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_ERROR = 'LOAD_NOTIFICATIONS_ERROR';

export const CREATE_USER_FOR_OFFICEADMIN = 'CREATE_USER_FOR_OFFICEADMIN';
export const CREATE_USER_FOR_OFFICEADMIN_FINISHED = 'CREATE_USER_FOR_OFFICEADMIN_FINISHED';

export const REMOVE_OFFICE_USER = 'REMOVE_OFFICE_USER';
export const REMOVE_OFFICE_USER_FINISHED = 'REMOVE_OFFICE_USER_FINISHED';

export const EDIT_OFFICE_USER = 'EDIT_OFFICE_USER';
export const EDIT_OFFICE_USER_FINISHED = 'EDIT_OFFICE_USER_FINISHED';

export const ADD_CONF_ROOM = 'ADD_CONF_ROOM';
export const ADD_CONF_ROOM_FINISHED = 'ADD_CONF_ROOM_FINISHED';

export const EDIT_CONF_ROOM = 'EDIT_CONF_ROOM';
export const EDIT_CONF_ROOM_FINISHED = 'EDIT_CONF_ROOM_FINISHED';

export const ADD_HOT_DESK = 'ADD_HOT_DESK';
export const ADD_HOT_DESK_FINISHED = 'ADD_HOT_DESK_FINISHED';

export const EDIT_HOT_DESK = 'EDIT_HOT_DESK';
export const EDIT_HOT_DESK_FINISHED = 'EDIT_HOT_DESK_FINISHED';

export const LOAD_SPACE_INFO = 'LOAD_SPACE_INFO';
export const LOAD_SPACE_INFO_FINISHED = 'LOAD_SPACE_INFO_FINISHED';
export const LOAD_SPACE_INFO_FINISHED_ERROR = 'LOAD_SPACE_INFO_FINISHED_ERROR';

export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_FINISHED = 'CREATE_EVENT_FINISHED';

export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_FINISHED = 'EDIT_EVENT_FINISHED';
